"""
Growth Intelligence Layer — Phase 7.

Generates org-level weekly/monthly intelligence summaries.
Each summary is a structured JSON with:
  - top_performing_variants: ranked by engagement_rate
  - platform_trends: per-platform with delta vs prior period
  - posting_frequency: actual vs recommended
  - engagement_roi: Phase 6 engagement effectiveness
  - recommendations: prioritized, data-backed action items
  - health_score: 0-100 composite growth score

Summaries are generated by calling build_intelligence_summary() and
stored in growth.growth_intelligence_summaries for read-time serving
without heavy aggregation queries.

The health_score is computed from:
  - Publishing consistency (0-30 points): posting on schedule vs target freq
  - Engagement quality (0-25 points): avg engagement_rate vs benchmarks
  - Content variety (0-20 points): angle_type diversity
  - Engagement actions (0-15 points): Phase 6 engagement activity
  - Trend direction (0-10 points): improving vs declining vs flat

Platform engagement rate benchmarks (industry averages):
  LinkedIn:  0.8-2.0% good, >2.0% excellent
  X:         0.03-0.09% good, >0.09% excellent
  Instagram: 1.0-3.5% good, >3.5% excellent
  Facebook:  0.2-0.5% good, >0.5% excellent
"""

from __future__ import annotations

import json
import uuid
from datetime import date, timedelta
from typing import Optional

import asyncpg

from app.logging_config import get_logger
from app.openai_client import CRITIC_MODEL, chat_completion
from app.services.analytics.metrics_store import get_org_overview, get_top_content
from app.services.analytics.roi_attribution import get_engagement_roi_summary

log = get_logger(__name__)

INTELLIGENCE_MODEL = CRITIC_MODEL  # gpt-4o-mini

# Default internal heuristic thresholds for engagement rate by platform.
#
# These are INITIAL BASELINE values derived from broad B2B industry averages.
# They are NOT universal standards — actual benchmarks vary significantly by:
#   - niche and industry vertical
#   - audience size (larger accounts typically show lower rates)
#   - content type (video vs text vs image)
#   - account maturity and posting frequency
#
# Treat these as starting references for trend detection and health scoring,
# not as pass/fail criteria. Orgs can override these via org_growth_settings
# in a future release.
_DEFAULT_HEURISTIC_THRESHOLDS: dict[str, dict[str, float]] = {
    "linkedin":  {"baseline": 0.008, "strong": 0.020},
    "x":         {"baseline": 0.0003, "strong": 0.0009},
    "instagram": {"baseline": 0.010, "strong": 0.035},
    "facebook":  {"baseline": 0.002, "strong": 0.005},
}
# Alias for internal callers — named to surface the heuristic nature
_BENCHMARKS = _DEFAULT_HEURISTIC_THRESHOLDS


async def build_intelligence_summary(
    pool: asyncpg.Pool,
    org_id: uuid.UUID,
    period_type: str,        # 'weekly' | 'monthly'
    period_start: date,
    period_end: date,
) -> dict:
    """
    Build a full intelligence summary for the period.
    Stores the result in growth_intelligence_summaries and returns the summary dict.
    """
    # ── Gather data ───────────────────────────────────────────────────────────
    overview     = await get_org_overview(pool, org_id, period_start, period_end)
    top_content  = await get_top_content(pool, org_id, None, period_start, period_end, limit=10)
    engagement   = await get_engagement_roi_summary(pool, org_id, period_start, period_end)

    # Actual published post count from publish_queue — used by health score
    # when content_metrics is empty (no engagement data ingested yet).
    async with pool.acquire() as conn:
        pub_row = await conn.fetchrow(
            """
            SELECT COUNT(*) AS n
            FROM growth.publish_queue
            WHERE org_id = $1
              AND status = 'published'
              AND updated_at >= $2
            """,
            org_id, period_start,
        )
    queue_published_count = int(pub_row["n"]) if pub_row else 0

    # Prior period for trend comparison
    delta = period_end - period_start
    prior_start = period_start - delta - timedelta(days=1)
    prior_end   = period_start - timedelta(days=1)
    prior_overview = await get_org_overview(pool, org_id, prior_start, prior_end)

    # ── Build platform trends ─────────────────────────────────────────────────
    prior_map = {r["platform"]: r for r in prior_overview}
    platform_trends = []
    for row in overview:
        platform = row["platform"]
        prior    = prior_map.get(platform, {})
        prior_rate = float(prior.get("avg_engagement_rate", 0) or 0)
        curr_rate  = float(row["avg_engagement_rate"] or 0)
        delta_rate = curr_rate - prior_rate

        benchmark = _BENCHMARKS.get(platform, {"baseline": 0.005, "strong": 0.015})
        if curr_rate >= benchmark["strong"]:
            rating = "above_heuristic_strong"
        elif curr_rate >= benchmark["baseline"]:
            rating = "above_heuristic_baseline"
        else:
            rating = "below_heuristic_baseline"

        platform_trends.append({
            "platform":              platform,
            "avg_engagement_rate":   round(curr_rate, 4),
            "total_impressions":     row["total_impressions"],
            "total_posts":           row["posts_published"],
            "delta_vs_prior":        round(delta_rate, 4),
            "trend":                 "up" if delta_rate > 0 else ("flat" if abs(delta_rate) < 0.0001 else "down"),
            "benchmark_rating":      rating,
        })

    # ── Top performers ────────────────────────────────────────────────────────
    top_performers = [
        {
            "variant_id":       str(r["variant_id"]),
            "platform":         r["platform"],
            "angle_type":       r["angle_type"],
            "impressions":      r["impressions"],
            "engagement_rate":  round(float(r["engagement_rate"]), 4),
        }
        for r in top_content[:5]
    ]

    # ── Posting frequency ─────────────────────────────────────────────────────
    days_in_period = (period_end - period_start).days + 1
    posting_frequency = []
    for row in overview:
        actual = row["posts_published"]
        recommended = _recommended_frequency(row["platform"], period_type)
        posting_frequency.append({
            "platform":              row["platform"],
            "posts_published":       actual,
            "recommended_per_period": recommended,
            "on_track":              actual >= recommended,
        })

    # ── Health score ──────────────────────────────────────────────────────────
    health_score = _compute_health_score(
        overview, engagement, prior_overview, queue_published_count
    )

    # ── LLM recommendations ───────────────────────────────────────────────────
    recommendations = await _generate_recommendations(
        org_id=org_id,
        platform_trends=platform_trends,
        posting_frequency=posting_frequency,
        engagement_summary=engagement,
        health_score=health_score,
    )

    # ── Assemble summary ──────────────────────────────────────────────────────
    summary = {
        "top_performing_variants": top_performers,
        "platform_trends":         platform_trends,
        "posting_frequency":       posting_frequency,
        "engagement_roi": {
            "total_actions":        engagement["total_engagements"],
            "successful_actions":   engagement["successful_engagements"],
            "avg_confidence":       engagement["avg_confidence_score"],
            "avg_risk":             engagement["avg_risk_score"],
            "top_outcomes":         engagement["platforms"],
        },
        "recommendations":         recommendations,
        "health_score":            health_score,
    }

    # ── Store ─────────────────────────────────────────────────────────────────
    variants_analyzed = sum(r["posts_published"] for r in overview)
    await _upsert_summary(
        pool=pool,
        org_id=org_id,
        period_type=period_type,
        period_start=period_start,
        period_end=period_end,
        summary=summary,
        variants_analyzed=variants_analyzed,
    )

    log.info(
        "intelligence_summary_generated",
        org_id=str(org_id), period_type=period_type,
        period_start=period_start.isoformat(), health_score=health_score,
    )
    return summary


async def get_latest_summary(
    pool: asyncpg.Pool,
    org_id: uuid.UUID,
    period_type: str = "weekly",
) -> Optional[dict]:
    """Return the most recent stored summary for the org."""
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            """
            SELECT id, org_id, period_type, period_start, period_end,
                   summary_json, generated_at, variants_analyzed,
                   created_at, updated_at
            FROM growth.growth_intelligence_summaries
            WHERE org_id = $1 AND period_type = $2
            ORDER BY period_start DESC
            LIMIT 1
            """,
            org_id, period_type,
        )
    if not row:
        return None
    result = dict(row)
    # asyncpg may return jsonb columns as a raw string — parse defensively
    summary_json = result["summary_json"]
    if isinstance(summary_json, str):
        summary_json = json.loads(summary_json)
        result["summary_json"] = summary_json
    result["health_score"] = summary_json.get("health_score", 0.0)
    return result


# ── Internal helpers ─────────────────────────────────────────────────────────

def _recommended_frequency(platform: str, period_type: str) -> int:
    """Baseline recommended posts per period by platform."""
    weekly = {"linkedin": 3, "x": 5, "instagram": 4, "facebook": 3}
    monthly = {k: v * 4 for k, v in weekly.items()}
    table = monthly if period_type == "monthly" else weekly
    return table.get(platform, 3)


def _compute_health_score(
    overview: list[dict],
    engagement: dict,
    prior_overview: list[dict],
    queue_published_count: int = 0,
) -> float:
    """
    Compute composite health score 0-100.

    queue_published_count: actual published posts from publish_queue for the
    period. Used to give partial publishing credit when content_metrics is
    still empty (no engagement data ingested from the platform yet).
    """
    score = 0.0

    # Publishing consistency (0-30): posted at least 50% of recommended.
    # Falls back to queue_published_count when content_metrics is empty so
    # a brand-new org that has published posts scores > 0.
    if overview:
        on_track = sum(
            1 for r in overview
            if r["posts_published"] >= _recommended_frequency(r["platform"], "weekly") * 0.5
        )
        score += (on_track / len(overview)) * 30
    elif queue_published_count > 0:
        # No engagement metrics yet — give partial credit proportional to
        # posts published (caps at 15 pts; full 30 requires engagement data).
        score += min(queue_published_count / 3, 1.0) * 15

    # Engagement quality (0-25): any platform at "good" or better
    if overview:
        good_count = 0
        for row in overview:
            benchmark = _BENCHMARKS.get(row["platform"], {"baseline": 0.005})
            if float(row.get("avg_engagement_rate") or 0) >= benchmark["baseline"]:
                good_count += 1
        score += (good_count / len(overview)) * 25

    # Content variety (0-20): at least 2 platforms active
    active_platforms = len(overview)
    score += min(active_platforms / 3, 1.0) * 20

    # Engagement actions (0-15): at least 3 successful engagements
    succ = engagement.get("successful_engagements", 0)
    score += min(succ / 10, 1.0) * 15

    # Trend direction (0-10): more platforms improving than declining
    prior_map = {r["platform"]: r for r in prior_overview}
    if overview and prior_overview:
        improving = sum(
            1 for row in overview
            if float(row.get("avg_engagement_rate") or 0) >
               float(prior_map.get(row["platform"], {}).get("avg_engagement_rate") or 0)
        )
        score += (improving / len(overview)) * 10

    return round(min(score, 100.0), 1)


async def _generate_recommendations(
    org_id: uuid.UUID,
    platform_trends: list[dict],
    posting_frequency: list[dict],
    engagement_summary: dict,
    health_score: float,
) -> list[dict]:
    """Call LLM to generate 3-5 prioritized, data-backed recommendations."""
    context = {
        "health_score": health_score,
        "platform_trends": platform_trends,
        "posting_frequency": posting_frequency,
        "engagement_actions": engagement_summary.get("total_engagements", 0),
        "engagement_success_rate": (
            engagement_summary.get("successful_engagements", 0) /
            max(engagement_summary.get("total_engagements", 1), 1)
        ),
    }

    prompt = f"""\
You are a B2B social media growth strategist analyzing performance data.

Performance data:
{json.dumps(context, indent=2)}

Generate 3-5 specific, actionable recommendations to improve this org's social media growth.

Each recommendation must:
- Be grounded in the specific numbers shown
- Have a clear priority (high/medium/low)
- Include a category from: posting_frequency, content_type, platform_mix,
  engagement_strategy, timing, audience_targeting
- Be actionable in the next 7 days

Return JSON array:
[
  {{
    "priority": "high|medium|low",
    "category": "...",
    "action": "specific action to take",
    "reason": "why, referencing the data"
  }}
]"""

    try:
        raw = await chat_completion(
            messages=[{"role": "user", "content": prompt}],
            model=INTELLIGENCE_MODEL,
            temperature=0.4,
            max_tokens=800,
            response_format={"type": "json_object"},
        )
        parsed = json.loads(raw)
        # Handle both {recommendations: [...]} and direct [...]
        if isinstance(parsed, dict):
            recs = parsed.get("recommendations", list(parsed.values())[0] if parsed else [])
        else:
            recs = parsed
        return recs if isinstance(recs, list) else []
    except Exception as exc:
        log.warning("intelligence_recommendations_failed", error=str(exc))
        return [{
            "priority": "high",
            "category": "posting_frequency",
            "action": "Review your posting consistency — data analysis is available in your metrics dashboard.",
            "reason": "Recommendation generation encountered an error; default provided.",
        }]


async def _upsert_summary(
    pool: asyncpg.Pool,
    org_id: uuid.UUID,
    period_type: str,
    period_start: date,
    period_end: date,
    summary: dict,
    variants_analyzed: int,
) -> None:
    async with pool.acquire() as conn:
        await conn.execute(
            """
            INSERT INTO growth.growth_intelligence_summaries (
                org_id, period_type, period_start, period_end,
                summary_json, generation_model, variants_analyzed
            ) VALUES ($1, $2, $3, $4, $5::jsonb, $6, $7)
            ON CONFLICT (org_id, period_type, period_start)
            DO UPDATE SET
                summary_json      = EXCLUDED.summary_json,
                period_end        = EXCLUDED.period_end,
                generation_model  = EXCLUDED.generation_model,
                variants_analyzed = EXCLUDED.variants_analyzed,
                generated_at      = NOW(),
                updated_at        = NOW()
            """,
            org_id, period_type, period_start, period_end,
            json.dumps(summary), INTELLIGENCE_MODEL, variants_analyzed,
        )
